### ISSUE TITLE
Resolve leaks

### ISSUE THREAD

**Issue by agatocherry** [agatocherry/webserv#41]
### Description

Resolve leaks before start everything else, have a good and a clean project. Please be sure to check for every cases : errors, no calls, with one or others calls, and if the port is already use.

### Sub-tasks

- [x] Remove every useless files
- [x] No more errors (in any cases)
- [x] No more leaks, don't forget to do it step by step (in any cases) 
- [ ] Remove all useless comments
- [ ] Add new goods comments (for big methods)
